### ISSUE TITLE
API free time slot creation has timezone issue

### ISSUE THREAD

**Issue by ride90** [chcikrasu/api#12]
API free time slot creation has timezone issue

**Comment by ValeriiaTol** [comment]
Create method `updateFreeslot(id, serviceIds, itemsToUpdate)`

- if serviceIds are the same as existing freeSlot has, do nothing. (Probably user just clicked on Save without any changes by mistake (? maybe disable save button in case of no changes))
- iterate items of freeslot. If current item is among of `itemsToUpdate` => update existing free slot with end time before this item, create new free slot with old settings with begin time after this item. Create new freeslot from this item with new serviceIds.

**Comment by ride90** [comment]
done
