### ISSUE TITLE
deleteFreeSlot in api

### ISSUE THREAD

**Issue by ValeriiaTol** [chcikrasu/api#15]
Create method  `deleteFreeSlot (slotId, itemsToDelete: Array<Date>)`

- In this method iterate `itemsToDelete`. Find freeslot, that this item belongs to. 
- Check if this free slot is only 30minutes => we can delete it right a way. 
       
```
let slots30minsCount = Math.floor((Math.abs(new Date(freeSlot.end) - new Date(freeSlot.begin))/1000)/60) / 30;

// if it's 30 minutes freeslot -> delete 
 if (slots30minsCount == 1)
{
      deleteFreeSlot(freeSlot.id);
}
```

- Then check if item is at the beginning or at the end of free slot => we can update time of existing freeslot.

- If item is in the middle of free slot -> patch freeslot to end before this item. And create new freeslot after this item. It's important to await this action in case of multiple items in the middle.

**Comment by ride90** [comment]
@ValeriiaTol done

**Comment by ride90** [comment]
Request example:

curl -X DELETE \
  http://127.0.0.1:8888/api/calendars/free-slots/3/split/ \
  -H 'Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNTYsInVzZXJuYW1lIjoiZW1hQG5vdmFrb3ZhLmNvbSIsImV4cCI6MTU1MzU1MTk3NSwiZW1haWwiOiJlbWFAbm92YWtvdmEuY29tIiwib3JpZ19pYXQiOjE1NTM0MzY3NzV9.XxPBjQfHtHPkyxV0o26mPXj5oPobcUP96E_R2JxE6Kk' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: f1c000ae-f145-4648-bd72-a48d3ce6e3a5' \
  -H 'cache-control: no-cache' \
  -d '{
	"time_slots": [
		"2019-03-30T10:00:00",
		"2019-03-30T11:30:00",
		"2019-03-30T12:00:00",
		"2019-03-30T12:30:00",
		"2019-03-30T13:00:00",
		"2019-03-30T13:30:00",
		"2019-03-30T14:00:00",
		"2019-03-30T14:30:00",
		"2019-03-30T15:00:00",
		"2019-03-30T18:30:00"
		]
}'
